# Generated by Django 5.2.7 on 2025-11-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostoEnvioComuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=100, unique=True)),
                ('costo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costo de Envío por Comuna',
                'verbose_name_plural': 'Costos de Envío por Comuna',
                'db_table': 'costo_envio_comuna',
                'ordering': ['comuna'],
            },
        ),
    ]
