/*
SCRIPT PARA CREAR LAS TABLAS DE LA BASE DE DATOS CORDILLERAPETS - POSTGRESQL
*/

-- DROP TYPE public."estado_metodo";

CREATE TYPE public."estado_metodo" AS ENUM (
	'activo',
	'inactivo',
	'vencido');

-- DROP TYPE public."estado_pedido";

CREATE TYPE public."estado_pedido" AS ENUM (
	'Pendiente de pago',
	'Procesando',
	'Despachado',
	'Entregado',
	'Entrega fallida',
	'Cancelado',
	'Reembolsado');

-- DROP TYPE public."estado_producto";

CREATE TYPE public."estado_producto" AS ENUM (
	'activo',
	'inactivo',
	'eliminado');

-- DROP TYPE public."estado_sesion";

CREATE TYPE public."estado_sesion" AS ENUM (
	'activa',
	'convertida',
	'expirada');

-- DROP TYPE public."estado_transaccion";

CREATE TYPE public."estado_transaccion" AS ENUM (
	'pendiente',
	'pagado',
	'error');

-- DROP TYPE public."tipo_documento";

CREATE TYPE public."tipo_documento" AS ENUM (
	'boleta',
	'factura');

-- DROP TYPE public."tipo_metodo_pago";

CREATE TYPE public."tipo_metodo_pago" AS ENUM (
	'tarjeta_credito',
	'tarjeta_debito',
	'cuenta_corriente');

-- DROP TYPE public."tipo_operacion";

CREATE TYPE public."tipo_operacion" AS ENUM (
	'venta',
	'ingreso',
	'ajuste',
	'devolucion',
	'merma');

-- public.cliente_empresa definition

-- Drop table

-- DROP TABLE public.cliente_empresa;

CREATE TABLE public.cliente_empresa (
	cliente_empresa_id serial4 NOT NULL,
	rut_empresa varchar(12) NOT NULL,
	razon_social varchar(100) NOT NULL,
	giro varchar(50) NOT NULL,
	email_contacto varchar(50) NOT NULL,
	telefono_contacto varchar(20) NOT NULL,
	representante_legal varchar(50) NOT NULL,
	fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado bool DEFAULT true NOT NULL,
	contrasena varchar NOT NULL,
	CONSTRAINT cliente_empresa_email_contacto_key UNIQUE (email_contacto),
	CONSTRAINT cliente_empresa_pkey PRIMARY KEY (cliente_empresa_id),
	CONSTRAINT cliente_empresa_rut_empresa_key UNIQUE (rut_empresa)
);
CREATE INDEX idx_cliente_empresa_email ON public.cliente_empresa USING btree (email_contacto);


-- public.cliente_persona definition

-- Drop table

-- DROP TABLE public.cliente_persona;

CREATE TABLE public.cliente_persona (
	cliente_persona_id serial4 NOT NULL,
	rut varchar(12) NOT NULL,
	nombres varchar(25) NOT NULL,
	apellido_paterno varchar(25) NOT NULL,
	apellido_materno varchar(25) NOT NULL,
	email varchar(50) NOT NULL,
	telefono varchar(10) NOT NULL,
	fecha_nacimiento date NOT NULL,
	fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado bool DEFAULT true NOT NULL,
	"password" varchar NOT NULL,
	CONSTRAINT cliente_persona_email_key UNIQUE (email),
	CONSTRAINT cliente_persona_pkey PRIMARY KEY (cliente_persona_id),
	CONSTRAINT cliente_persona_rut_key UNIQUE (rut)
);
CREATE INDEX idx_cliente_persona_email ON public.cliente_persona USING btree (email);


-- public.marca definition

-- Drop table

-- DROP TABLE public.marca;

CREATE TABLE public.marca (
	marca_id serial4 NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	logo_url varchar(50) NULL,
	sitio_web varchar(50) NULL,
	slug varchar(50) NOT NULL,
	activa bool DEFAULT true NOT NULL,
	CONSTRAINT marca_nombre_key UNIQUE (nombre),
	CONSTRAINT marca_pkey PRIMARY KEY (marca_id),
	CONSTRAINT marca_slug_key UNIQUE (slug)
);
CREATE INDEX idx_marca_activa ON public.marca USING btree (activa);
CREATE INDEX idx_marca_slug ON public.marca USING btree (slug);


-- public.sesion_invitado definition

-- Drop table

-- DROP TABLE public.sesion_invitado;

CREATE TABLE public.sesion_invitado (
	cliente_invitado_id serial4 NOT NULL,
	session_id varchar(255) NOT NULL,
	nombres varchar(25) NOT NULL,
	apellido_paterno varchar(25) NOT NULL,
	apellido_materno varchar(25) NULL,
	email varchar(50) NOT NULL,
	telefono varchar(10) NOT NULL,
	calle_envio varchar(50) NOT NULL,
	ciudad_envio varchar(50) NOT NULL,
	region_envio varchar(50) NOT NULL,
	codigo_postal_envio int2 NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_sesion" DEFAULT 'activa'::estado_sesion NOT NULL,
	CONSTRAINT sesion_invitado_pkey PRIMARY KEY (cliente_invitado_id),
	CONSTRAINT sesion_invitado_session_id_key UNIQUE (session_id)
);


-- public.usuario_admin definition

-- Drop table

-- DROP TABLE public.usuario_admin;

CREATE TABLE public.usuario_admin (
	admin_id serial4 NOT NULL,
	nombre varchar(200) NOT NULL,
	email varchar(200) NOT NULL,
	password_hash varchar(255) NOT NULL,
	rol varchar(50) DEFAULT 'admin'::character varying NOT NULL,
	CONSTRAINT usuario_admin_email_key UNIQUE (email),
	CONSTRAINT usuario_admin_pkey PRIMARY KEY (admin_id)
);


-- public.ventas_producto definition

-- Drop table

-- DROP TABLE public.ventas_producto;

CREATE TABLE public.ventas_producto (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(200) NOT NULL,
	precio numeric(10, 2) NOT NULL,
	imagen varchar(100) NULL,
	stock int4 NOT NULL,
	CONSTRAINT ventas_producto_pkey PRIMARY KEY (id)
);


-- public.categoria definition

-- Drop table

-- DROP TABLE public.categoria;

CREATE TABLE public.categoria (
	categoria_id serial4 NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	categoria_padre_id int4 NULL,
	nivel int4 DEFAULT 1 NOT NULL,
	slug varchar(50) NULL,
	activa bool DEFAULT true NOT NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (categoria_id),
	CONSTRAINT categoria_slug_key UNIQUE (slug),
	CONSTRAINT chk_categoria_principal CHECK ((((nivel = 1) AND (categoria_padre_id IS NULL)) OR ((nivel = 2) AND (categoria_padre_id IS NOT NULL)))),
	CONSTRAINT chk_nivel_valido CHECK ((nivel = ANY (ARRAY[1, 2]))),
	CONSTRAINT uk_nombre_categoria UNIQUE (nombre, categoria_padre_id),
	CONSTRAINT fk_categoria_padre FOREIGN KEY (categoria_padre_id) REFERENCES public.categoria(categoria_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_categoria_activa ON public.categoria USING btree (activa);
CREATE INDEX idx_categoria_nivel ON public.categoria USING btree (nivel);
CREATE INDEX idx_categoria_padre ON public.categoria USING btree (categoria_padre_id);
CREATE INDEX idx_categoria_slug ON public.categoria USING btree (slug);


-- public.direccion definition

-- Drop table

-- DROP TABLE public.direccion;

CREATE TABLE public.direccion (
	direccion_id serial4 NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	calle varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	codigo_postal int2 NOT NULL,
	telefono varchar(10) NOT NULL,
	CONSTRAINT chk_direccion_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL)))),
	CONSTRAINT direccion_pkey PRIMARY KEY (direccion_id),
	CONSTRAINT fk_direccion_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_direccion_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- public.metodo_pago definition

-- Drop table

-- DROP TABLE public.metodo_pago;

CREATE TABLE public.metodo_pago (
	metodo_pago_id serial4 NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	tipo_metodo public."tipo_metodo_pago" NOT NULL,
	token_seguro varchar(50) NOT NULL,
	ultimos_4_digitos varchar(4) NOT NULL,
	nombre_titular varchar(50) NOT NULL,
	fecha_vencimiento date NOT NULL,
	estado public."estado_metodo" DEFAULT 'activo'::estado_metodo NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL)))),
	CONSTRAINT metodo_pago_pkey PRIMARY KEY (metodo_pago_id),
	CONSTRAINT fk_metodo_pago_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_metodo_pago_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- public.pedido definition

-- Drop table

-- DROP TABLE public.pedido;

CREATE TABLE public.pedido (
	pedido_id bigserial NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	cliente_invitado_id int4 NULL,
	calle varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	codigo_postal int2 NULL,
	fecha timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_pedido" DEFAULT 'Pendiente de pago'::estado_pedido NOT NULL,
	total int4 NOT NULL,
	notas text NULL,
	tracking_codigo varchar(50) NULL,
	CONSTRAINT chk_pedido_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL) AND (cliente_invitado_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL) AND (cliente_invitado_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NULL) AND (cliente_invitado_id IS NOT NULL)))),
	CONSTRAINT pedido_pkey PRIMARY KEY (pedido_id),
	CONSTRAINT pedido_total_check CHECK ((total >= 0)),
	CONSTRAINT fk_pedido_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_sesion_invitado FOREIGN KEY (cliente_invitado_id) REFERENCES public.sesion_invitado(cliente_invitado_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_pedido_cliente_empresa ON public.pedido USING btree (cliente_empresa_id);
CREATE INDEX idx_pedido_cliente_invitado ON public.pedido USING btree (cliente_invitado_id);
CREATE INDEX idx_pedido_cliente_persona ON public.pedido USING btree (cliente_persona_id);
CREATE INDEX idx_pedido_estado ON public.pedido USING btree (estado);
CREATE INDEX idx_pedido_fecha ON public.pedido USING btree (fecha);


-- public.pedido_registro definition

-- Drop table

-- DROP TABLE public.pedido_registro;

CREATE TABLE public.pedido_registro (
	registro_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	fecha_registro date DEFAULT CURRENT_DATE NOT NULL,
	estado_anterior public."estado_pedido" NOT NULL,
	estado_actual public."estado_pedido" NOT NULL,
	CONSTRAINT chk_cambio_estado_pedido CHECK ((estado_anterior <> estado_actual)),
	CONSTRAINT pedido_registro_pkey PRIMARY KEY (registro_id),
	CONSTRAINT fk_pedido_registro_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- public.producto definition

-- Drop table

-- DROP TABLE public.producto;

CREATE TABLE public.producto (
	producto_id serial4 NOT NULL,
	categoria_id int4 NOT NULL,
	sku varchar(50) NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	precio int4 NOT NULL,
	stock int4 DEFAULT 0 NOT NULL,
	imagen_url text NULL,
	fecha_creation timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"estado_producto" public."estado_producto" DEFAULT 'activo'::estado_producto NOT NULL,
	marca_id int4 NULL,
	slug varchar(50) NULL,
	CONSTRAINT producto_pkey PRIMARY KEY (producto_id),
	CONSTRAINT producto_precio_check CHECK ((precio >= 0)),
	CONSTRAINT producto_sku_key UNIQUE (sku),
	CONSTRAINT producto_stock_check CHECK ((stock >= 0)),
	CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES public.categoria(categoria_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES public.marca(marca_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_producto_categoria ON public.producto USING btree (categoria_id);
CREATE INDEX idx_producto_marca ON public.producto USING btree (marca_id);
CREATE INDEX idx_producto_sku ON public.producto USING btree (sku);


-- public.sucursal definition

-- Drop table

-- DROP TABLE public.sucursal;

CREATE TABLE public.sucursal (
	sucursal_id serial4 NOT NULL,
	admin_responsable_id int4 NOT NULL,
	nombre varchar(50) NOT NULL,
	direccion text NOT NULL,
	telefono varchar(20) NULL,
	email varchar(50) NULL,
	estado bool DEFAULT true NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT sucursal_nombre_key UNIQUE (nombre),
	CONSTRAINT sucursal_pkey PRIMARY KEY (sucursal_id),
	CONSTRAINT fk_sucursal_admin FOREIGN KEY (admin_responsable_id) REFERENCES public.usuario_admin(admin_id) ON DELETE RESTRICT ON UPDATE CASCADE
);


-- public.vendedor definition

-- Drop table

-- DROP TABLE public.vendedor;

CREATE TABLE public.vendedor (
	vendedor_id serial4 NOT NULL,
	sucursal_id int4 NOT NULL,
	nombres varchar(25) NOT NULL,
	apellido_paterno varchar(25) NOT NULL,
	apellido_materno varchar(25) NULL,
	email varchar(50) NOT NULL,
	telefono varchar(10) NULL,
	estado bool DEFAULT true NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT vendedor_email_key UNIQUE (email),
	CONSTRAINT vendedor_pkey PRIMARY KEY (vendedor_id),
	CONSTRAINT fk_vendedor_sucursal FOREIGN KEY (sucursal_id) REFERENCES public.sucursal(sucursal_id) ON DELETE RESTRICT ON UPDATE CASCADE
);


-- public.documento_tributario definition

-- Drop table

-- DROP TABLE public.documento_tributario;

CREATE TABLE public.documento_tributario (
	documento_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	"tipo_documento" public."tipo_documento" NOT NULL,
	folio int4 NULL,
	fecha_emision timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	subtotal int4 NOT NULL,
	total int4 NOT NULL,
	rut_cliente varchar(12) NULL,
	nombre_cliente varchar(45) NULL,
	rut_empresa varchar(12) NULL,
	razon_social varchar(100) NULL,
	giro varchar(255) NULL,
	direccion_facturacion text NULL,
	CONSTRAINT chk_boleta_campos CHECK (((tipo_documento <> 'boleta'::tipo_documento) OR ((rut_cliente IS NOT NULL) AND (nombre_cliente IS NOT NULL)))),
	CONSTRAINT chk_factura_campos CHECK (((tipo_documento <> 'factura'::tipo_documento) OR ((rut_empresa IS NOT NULL) AND (razon_social IS NOT NULL) AND (giro IS NOT NULL)))),
	CONSTRAINT documento_tributario_pedido_id_key UNIQUE (pedido_id),
	CONSTRAINT documento_tributario_pkey PRIMARY KEY (documento_id),
	CONSTRAINT documento_tributario_subtotal_check CHECK ((subtotal >= 0)),
	CONSTRAINT documento_tributario_total_check CHECK ((total >= 0)),
	CONSTRAINT fk_documento_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_documento_pedido ON public.documento_tributario USING btree (pedido_id);


-- public.movimiento_estado definition

-- Drop table

-- DROP TABLE public.movimiento_estado;

CREATE TABLE public.movimiento_estado (
	movimiento_estado_id serial4 NOT NULL,
	producto_id int4 NOT NULL,
	fecha_movimiento timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado_anterior public."estado_producto" NOT NULL,
	estado_actual public."estado_producto" NOT NULL,
	CONSTRAINT chk_cambio_estado CHECK ((estado_anterior <> estado_actual)),
	CONSTRAINT movimiento_estado_pkey PRIMARY KEY (movimiento_estado_id),
	CONSTRAINT fk_movimiento_estado_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- public.movimiento_stock definition

-- Drop table

-- DROP TABLE public.movimiento_stock;

CREATE TABLE public.movimiento_stock (
	movimiento_stock_id bigserial NOT NULL,
	producto_id int4 NOT NULL,
	cantidad int4 NOT NULL,
	fecha_movimiento timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"tipo_operacion" public."tipo_operacion" NOT NULL,
	CONSTRAINT movimiento_stock_pkey PRIMARY KEY (movimiento_stock_id),
	CONSTRAINT fk_movimiento_stock_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_movimiento_stock_fecha ON public.movimiento_stock USING btree (fecha_movimiento);
CREATE INDEX idx_movimiento_stock_producto ON public.movimiento_stock USING btree (producto_id);


-- public.pago definition

-- Drop table

-- DROP TABLE public.pago;

CREATE TABLE public.pago (
	pago_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	monto int4 NOT NULL,
	metodo varchar(50) NOT NULL,
	estado varchar(50) NOT NULL,
	transbank_token varchar(50) NULL,
	fecha timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT pago_monto_check CHECK ((monto > 0)),
	CONSTRAINT pago_pkey PRIMARY KEY (pago_id),
	CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_pago_pedido ON public.pago USING btree (pedido_id);


-- public.pedido_item definition

-- Drop table

-- DROP TABLE public.pedido_item;

CREATE TABLE public.pedido_item (
	pedido_item_id bigserial NOT NULL,
	producto_id int4 NOT NULL,
	pedido_id int8 NOT NULL,
	cantidad int4 NOT NULL,
	precio_unitario int4 NOT NULL,
	subtotal int4 NOT NULL,
	CONSTRAINT pedido_item_cantidad_check CHECK ((cantidad > 0)),
	CONSTRAINT pedido_item_pkey PRIMARY KEY (pedido_item_id),
	CONSTRAINT pedido_item_precio_unitario_check CHECK ((precio_unitario >= 0)),
	CONSTRAINT pedido_item_subtotal_check CHECK ((subtotal >= 0)),
	CONSTRAINT fk_pedido_item_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_item_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE RESTRICT ON UPDATE CASCADE
);
