# Generated by Django 5.2.7 on 2025-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('cliente_empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=50)),
                ('email_contacto', models.CharField(max_length=50, unique=True)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('representante_legal', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cliente_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientePersona',
            fields=[
                ('cliente_persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cliente_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('codigo_postal', models.SmallIntegerField()),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('documento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rut_cliente', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=12, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_facturacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_tributario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_metodo', models.CharField(max_length=50)),
                ('token_seguro', models.CharField(max_length=50)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('nombre_titular', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoEstado',
            fields=[
                ('movimiento_estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_actual', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movimiento_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('movimiento_stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_operacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movimiento_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('metodo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('transbank_token', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('codigo_postal', models.SmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente de pago', max_length=50)),
                ('total', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('tracking_codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('pedido_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'pedido_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoRegistro',
            fields=[
                ('registro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_actual', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pedido_registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionInvitado',
            fields=[
                ('cliente_invitado_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('calle_envio', models.CharField(max_length=50)),
                ('ciudad_envio', models.CharField(max_length=50)),
                ('region_envio', models.CharField(max_length=50)),
                ('codigo_postal_envio', models.SmallIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activa', max_length=50)),
            ],
            options={
                'db_table': 'sesion_invitado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(default='admin', max_length=50)),
            ],
            options={
                'db_table': 'usuario_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
