# Generated by Django 5.2.7 on 2025-10-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_categoria_clienteempresa_clientepersona_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
