-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE public.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE public.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE public.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

-- Drop table

-- DROP TABLE public.auth_user;

CREATE TABLE public.auth_user (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	CONSTRAINT auth_user_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

-- Drop table

-- DROP TABLE public.auth_user_groups;

CREATE TABLE public.auth_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id),
	CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);

-- Drop table

-- DROP TABLE public.auth_user_user_permissions;

CREATE TABLE public.auth_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);

-- Drop table

-- DROP TABLE public.categoria;

CREATE TABLE public.categoria (
	categoria_id serial4 NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	categoria_padre_id int4 NULL,
	nivel int4 DEFAULT 1 NOT NULL,
	slug varchar(50) NULL,
	activa bool DEFAULT true NOT NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (categoria_id),
	CONSTRAINT categoria_slug_key UNIQUE (slug),
	CONSTRAINT chk_categoria_principal CHECK ((((nivel = 1) AND (categoria_padre_id IS NULL)) OR ((nivel = 2) AND (categoria_padre_id IS NOT NULL)))),
	CONSTRAINT chk_nivel_valido CHECK ((nivel = ANY (ARRAY[1, 2]))),
	CONSTRAINT uk_nombre_categoria UNIQUE (nombre, categoria_padre_id),
	CONSTRAINT fk_categoria_padre FOREIGN KEY (categoria_padre_id) REFERENCES public.categoria(categoria_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_categoria_activa ON public.categoria USING btree (activa);
CREATE INDEX idx_categoria_nivel ON public.categoria USING btree (nivel);
CREATE INDEX idx_categoria_padre ON public.categoria USING btree (categoria_padre_id);
CREATE INDEX idx_categoria_slug ON public.categoria USING btree (slug);

-- Drop table

-- DROP TABLE public.checkout_session;

CREATE TABLE public.checkout_session (
	id serial4 NOT NULL,
	session_id varchar(255) NOT NULL,
	nombres varchar(100) NOT NULL,
	apellidos varchar(100) NOT NULL,
	email varchar(254) NOT NULL,
	telefono varchar(20) NOT NULL,
	rut varchar(11) NOT NULL,
	calle varchar(100) NOT NULL,
	ciudad varchar(100) NOT NULL,
	region varchar(100) NOT NULL,
	codigo_postal varchar(10) NULL,
	total int4 NOT NULL,
	subtotal int4 NOT NULL,
	costo_envio int4 DEFAULT 2990 NOT NULL,
	transbank_token varchar(255) NULL,
	transbank_url text NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	carrito_data jsonb NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	fecha_actualizacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_transaccion" DEFAULT 'pendiente'::estado_transaccion NOT NULL,
	CONSTRAINT checkout_session_pkey PRIMARY KEY (id),
	CONSTRAINT checkout_session_session_id_key UNIQUE (session_id)
);
CREATE INDEX idx_checkout_cliente_empresa ON public.checkout_session USING btree (cliente_empresa_id);
CREATE INDEX idx_checkout_cliente_persona ON public.checkout_session USING btree (cliente_persona_id);
CREATE INDEX idx_checkout_fecha_creacion ON public.checkout_session USING btree (fecha_creacion);
CREATE INDEX idx_checkout_session_id ON public.checkout_session USING btree (session_id);
CREATE INDEX idx_checkout_token ON public.checkout_session USING btree (transbank_token);

-- Drop table

-- DROP TABLE public.cliente_empresa;

CREATE TABLE public.cliente_empresa (
	cliente_empresa_id serial4 NOT NULL,
	rut_empresa varchar(11) NOT NULL,
	razon_social varchar(100) NOT NULL,
	giro varchar(50) NOT NULL,
	email_contacto varchar(50) NOT NULL,
	telefono_contacto varchar(20) NOT NULL,
	representante_legal varchar(50) NOT NULL,
	fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado bool DEFAULT true NOT NULL,
	contrasena varchar NOT NULL,
	CONSTRAINT cliente_empresa_email_contacto_key UNIQUE (email_contacto),
	CONSTRAINT cliente_empresa_pkey PRIMARY KEY (cliente_empresa_id),
	CONSTRAINT cliente_empresa_rut_empresa_key UNIQUE (rut_empresa)
);
CREATE INDEX idx_cliente_empresa_email ON public.cliente_empresa USING btree (email_contacto);

-- Drop table

-- DROP TABLE public.cliente_persona;

CREATE TABLE public.cliente_persona (
	cliente_persona_id serial4 NOT NULL,
	rut varchar(11) NOT NULL,
	nombres varchar(25) NOT NULL,
	apellido_paterno varchar(25) NOT NULL,
	apellido_materno varchar(25) NOT NULL,
	email varchar(50) NOT NULL,
	telefono varchar(10) NOT NULL,
	fecha_nacimiento date NOT NULL,
	fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado bool DEFAULT true NOT NULL,
	"password" varchar NOT NULL,
	CONSTRAINT cliente_persona_email_key UNIQUE (email),
	CONSTRAINT cliente_persona_pkey PRIMARY KEY (cliente_persona_id),
	CONSTRAINT cliente_persona_rut_key UNIQUE (rut)
);
CREATE INDEX idx_cliente_persona_email ON public.cliente_persona USING btree (email);

-- Drop table

-- DROP TABLE public.costo_envio_comuna;

CREATE TABLE public.costo_envio_comuna (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	comuna varchar(100) NOT NULL,
	costo int4 NOT NULL,
	activo bool NOT NULL,
	fecha_actualizacion timestamptz NOT NULL,
	CONSTRAINT costo_envio_comuna_comuna_key UNIQUE (comuna),
	CONSTRAINT costo_envio_comuna_pkey PRIMARY KEY (id)
);
CREATE INDEX costo_envio_comuna_comuna_287a563b_like ON public.costo_envio_comuna USING btree (comuna varchar_pattern_ops);

-- Drop table

-- DROP TABLE public.direccion;

CREATE TABLE public.direccion (
	direccion_id serial4 NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	calle varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	codigo_postal int4 NULL,
	telefono varchar(10) NOT NULL,
	CONSTRAINT chk_direccion_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL)))),
	CONSTRAINT direccion_pkey PRIMARY KEY (direccion_id),
	CONSTRAINT fk_direccion_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_direccion_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE public.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id int4 NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE public.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE public.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

-- Drop table

-- DROP TABLE public.documento_tributario;

CREATE TABLE public.documento_tributario (
	documento_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	"tipo_documento" public."tipo_documento" NOT NULL,
	folio int4 NULL,
	fecha_emision timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	subtotal int4 NOT NULL,
	total int4 NOT NULL,
	rut_cliente varchar(12) NULL,
	nombre_cliente varchar(45) NULL,
	rut_empresa varchar(12) NULL,
	razon_social varchar(100) NULL,
	giro varchar(255) NULL,
	direccion_facturacion text NULL,
	CONSTRAINT chk_boleta_campos CHECK (((tipo_documento <> 'boleta'::tipo_documento) OR ((rut_cliente IS NOT NULL) AND (nombre_cliente IS NOT NULL)))),
	CONSTRAINT chk_factura_campos CHECK (((tipo_documento <> 'factura'::tipo_documento) OR ((rut_empresa IS NOT NULL) AND (razon_social IS NOT NULL) AND (giro IS NOT NULL)))),
	CONSTRAINT documento_tributario_pedido_id_key UNIQUE (pedido_id),
	CONSTRAINT documento_tributario_pkey PRIMARY KEY (documento_id),
	CONSTRAINT documento_tributario_subtotal_check CHECK ((subtotal >= 0)),
	CONSTRAINT documento_tributario_total_check CHECK ((total >= 0)),
	CONSTRAINT fk_documento_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_documento_pedido ON public.documento_tributario USING btree (pedido_id);

-- Drop table

-- DROP TABLE public.marca;

CREATE TABLE public.marca (
	marca_id serial4 NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	logo_url text NULL,
	sitio_web varchar(50) NULL,
	slug varchar(50) NOT NULL,
	activa bool DEFAULT true NOT NULL,
	CONSTRAINT marca_nombre_key UNIQUE (nombre),
	CONSTRAINT marca_pkey PRIMARY KEY (marca_id),
	CONSTRAINT marca_slug_key UNIQUE (slug)
);
CREATE INDEX idx_marca_activa ON public.marca USING btree (activa);
CREATE INDEX idx_marca_slug ON public.marca USING btree (slug);

-- Drop table

-- DROP TABLE public.metodo_pago;

CREATE TABLE public.metodo_pago (
	metodo_pago_id serial4 NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	tipo_metodo public."tipo_metodo_pago" NOT NULL,
	token_seguro varchar(50) NOT NULL,
	ultimos_4_digitos varchar(4) NOT NULL,
	nombre_titular varchar(50) NOT NULL,
	fecha_vencimiento date NOT NULL,
	estado public."estado_metodo" DEFAULT 'activo'::estado_metodo NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chk_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL)))),
	CONSTRAINT metodo_pago_pkey PRIMARY KEY (metodo_pago_id),
	CONSTRAINT fk_metodo_pago_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_metodo_pago_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.movimiento_estado;

CREATE TABLE public.movimiento_estado (
	movimiento_estado_id serial4 NOT NULL,
	producto_id int4 NOT NULL,
	fecha_movimiento timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado_anterior public."estado_producto" NOT NULL,
	estado_actual public."estado_producto" NOT NULL,
	CONSTRAINT chk_cambio_estado CHECK ((estado_anterior <> estado_actual)),
	CONSTRAINT movimiento_estado_pkey PRIMARY KEY (movimiento_estado_id),
	CONSTRAINT fk_movimiento_estado_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.movimiento_stock;

CREATE TABLE public.movimiento_stock (
	movimiento_stock_id bigserial NOT NULL,
	producto_id int4 NOT NULL,
	cantidad int4 NOT NULL,
	fecha_movimiento timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"tipo_operacion" public."tipo_operacion" NOT NULL,
	CONSTRAINT movimiento_stock_pkey PRIMARY KEY (movimiento_stock_id),
	CONSTRAINT fk_movimiento_stock_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_movimiento_stock_fecha ON public.movimiento_stock USING btree (fecha_movimiento);
CREATE INDEX idx_movimiento_stock_producto ON public.movimiento_stock USING btree (producto_id);

-- Drop table

-- DROP TABLE public.pago;

CREATE TABLE public.pago (
	pago_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	monto int4 NOT NULL,
	metodo varchar(50) NOT NULL,
	transbank_token varchar(64) NOT NULL,
	fecha timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_transaccion" DEFAULT 'pendiente'::estado_transaccion NOT NULL,
	CONSTRAINT pago_monto_check CHECK ((monto > 0)),
	CONSTRAINT pago_pkey PRIMARY KEY (pago_id),
	CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_pago_pedido ON public.pago USING btree (pedido_id);

-- Drop table

-- DROP TABLE public.pedido;

CREATE TABLE public.pedido (
	pedido_id bigserial NOT NULL,
	cliente_persona_id int4 NULL,
	cliente_empresa_id int4 NULL,
	cliente_invitado_id int4 NULL,
	calle varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	codigo_postal int4 NULL,
	fecha timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_pedido" DEFAULT 'Pendiente de pago'::estado_pedido NOT NULL,
	total int4 NOT NULL,
	notas text NULL,
	tracking_codigo varchar(50) NULL,
	precio_envio int4 NULL,
	CONSTRAINT chk_pedido_cliente_unico CHECK ((((cliente_persona_id IS NOT NULL) AND (cliente_empresa_id IS NULL) AND (cliente_invitado_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NOT NULL) AND (cliente_invitado_id IS NULL)) OR ((cliente_persona_id IS NULL) AND (cliente_empresa_id IS NULL) AND (cliente_invitado_id IS NOT NULL)))),
	CONSTRAINT pedido_pkey PRIMARY KEY (pedido_id),
	CONSTRAINT pedido_total_check CHECK ((total >= 0)),
	CONSTRAINT fk_pedido_cliente_empresa FOREIGN KEY (cliente_empresa_id) REFERENCES public.cliente_empresa(cliente_empresa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_cliente_persona FOREIGN KEY (cliente_persona_id) REFERENCES public.cliente_persona(cliente_persona_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_sesion_invitado FOREIGN KEY (cliente_invitado_id) REFERENCES public.sesion_invitado(cliente_invitado_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_pedido_cliente_empresa ON public.pedido USING btree (cliente_empresa_id);
CREATE INDEX idx_pedido_cliente_invitado ON public.pedido USING btree (cliente_invitado_id);
CREATE INDEX idx_pedido_cliente_persona ON public.pedido USING btree (cliente_persona_id);
CREATE INDEX idx_pedido_estado ON public.pedido USING btree (estado);
CREATE INDEX idx_pedido_fecha ON public.pedido USING btree (fecha);

-- Drop table

-- DROP TABLE public.pedido_item;

CREATE TABLE public.pedido_item (
	pedido_item_id bigserial NOT NULL,
	producto_id int4 NOT NULL,
	pedido_id int8 NOT NULL,
	cantidad int4 NOT NULL,
	precio_unitario int4 NOT NULL,
	subtotal int4 NOT NULL,
	CONSTRAINT pedido_item_cantidad_check CHECK ((cantidad > 0)),
	CONSTRAINT pedido_item_pkey PRIMARY KEY (pedido_item_id),
	CONSTRAINT pedido_item_precio_unitario_check CHECK ((precio_unitario >= 0)),
	CONSTRAINT pedido_item_subtotal_check CHECK ((subtotal >= 0)),
	CONSTRAINT fk_pedido_item_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedido_item_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.pedido_registro;

CREATE TABLE public.pedido_registro (
	registro_id bigserial NOT NULL,
	pedido_id int8 NOT NULL,
	fecha_registro date DEFAULT CURRENT_DATE NOT NULL,
	estado_anterior public."estado_pedido" NOT NULL,
	estado_actual public."estado_pedido" NOT NULL,
	CONSTRAINT chk_cambio_estado_pedido CHECK ((estado_anterior <> estado_actual)),
	CONSTRAINT pedido_registro_pkey PRIMARY KEY (registro_id),
	CONSTRAINT fk_pedido_registro_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedido(pedido_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.producto;

CREATE TABLE public.producto (
	producto_id serial4 NOT NULL,
	categoria_id int4 NOT NULL,
	sku varchar(50) NOT NULL,
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	precio int4 NOT NULL,
	stock int4 DEFAULT 0 NOT NULL,
	imagen_url text NULL,
	fecha_creation timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"estado_producto" public."estado_producto" DEFAULT 'activo'::estado_producto NOT NULL,
	marca_id int4 NULL,
	slug varchar(50) NULL,
	CONSTRAINT producto_pkey PRIMARY KEY (producto_id),
	CONSTRAINT producto_precio_check CHECK ((precio >= 0)),
	CONSTRAINT producto_sku_key UNIQUE (sku),
	CONSTRAINT producto_stock_check CHECK ((stock >= 0)),
	CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES public.categoria(categoria_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES public.marca(marca_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_producto_categoria ON public.producto USING btree (categoria_id);
CREATE INDEX idx_producto_marca ON public.producto USING btree (marca_id);
CREATE INDEX idx_producto_sku ON public.producto USING btree (sku);

-- Drop table

-- DROP TABLE public.sesion_invitado;

CREATE TABLE public.sesion_invitado (
	cliente_invitado_id serial4 NOT NULL,
	email varchar(50) NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	estado public."estado_sesion" DEFAULT 'activa'::estado_sesion NOT NULL,
	rut varchar(11) NOT NULL,
	CONSTRAINT sesion_invitado_email_key UNIQUE (email),
	CONSTRAINT sesion_invitado_pkey PRIMARY KEY (cliente_invitado_id)
);

-- Drop table

-- DROP TABLE public.sucursal;

CREATE TABLE public.sucursal (
	sucursal_id serial4 NOT NULL,
	admin_responsable_id int4 NOT NULL,
	nombre varchar(50) NOT NULL,
	direccion text NOT NULL,
	telefono varchar(20) NULL,
	email varchar(50) NULL,
	estado bool DEFAULT true NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT sucursal_nombre_key UNIQUE (nombre),
	CONSTRAINT sucursal_pkey PRIMARY KEY (sucursal_id),
	CONSTRAINT fk_sucursal_admin FOREIGN KEY (admin_responsable_id) REFERENCES public.usuario_admin(admin_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.usuario_admin;

CREATE TABLE public.usuario_admin (
	admin_id serial4 NOT NULL,
	nombre varchar(200) NOT NULL,
	email varchar(200) NOT NULL,
	password_hash varchar(255) NOT NULL,
	rol varchar(50) DEFAULT 'admin'::character varying NOT NULL,
	CONSTRAINT usuario_admin_email_key UNIQUE (email),
	CONSTRAINT usuario_admin_pkey PRIMARY KEY (admin_id)
);

-- Drop table

-- DROP TABLE public.vendedor;

CREATE TABLE public.vendedor (
	vendedor_id serial4 NOT NULL,
	sucursal_id int4 NOT NULL,
	nombres varchar(25) NOT NULL,
	apellido_paterno varchar(25) NOT NULL,
	apellido_materno varchar(25) NULL,
	email varchar(50) NOT NULL,
	telefono varchar(10) NULL,
	estado bool DEFAULT true NOT NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT vendedor_email_key UNIQUE (email),
	CONSTRAINT vendedor_pkey PRIMARY KEY (vendedor_id),
	CONSTRAINT fk_vendedor_sucursal FOREIGN KEY (sucursal_id) REFERENCES public.sucursal(sucursal_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Drop table

-- DROP TABLE public.ventas_producto;

CREATE TABLE public.ventas_producto (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(200) NOT NULL,
	precio numeric(10, 2) NOT NULL,
	imagen varchar(100) NULL,
	stock int4 NOT NULL,
	CONSTRAINT ventas_producto_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.ventas_user;

CREATE TABLE public.ventas_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	email varchar(254) NOT NULL,
	CONSTRAINT ventas_user_email_key UNIQUE (email),
	CONSTRAINT ventas_user_pkey PRIMARY KEY (id),
	CONSTRAINT ventas_user_username_key UNIQUE (username)
);
CREATE INDEX ventas_user_email_79d10c80_like ON public.ventas_user USING btree (email varchar_pattern_ops);
CREATE INDEX ventas_user_username_f462e799_like ON public.ventas_user USING btree (username varchar_pattern_ops);

-- Drop table

-- DROP TABLE public.ventas_user_groups;

CREATE TABLE public.ventas_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT ventas_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT ventas_user_groups_user_id_group_id_2669f9a7_uniq UNIQUE (user_id, group_id),
	CONSTRAINT ventas_user_groups_group_id_1d8d7d58_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT ventas_user_groups_user_id_640e6cc0_fk_ventas_user_id FOREIGN KEY (user_id) REFERENCES public.ventas_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ventas_user_groups_group_id_1d8d7d58 ON public.ventas_user_groups USING btree (group_id);
CREATE INDEX ventas_user_groups_user_id_640e6cc0 ON public.ventas_user_groups USING btree (user_id);

-- Drop table

-- DROP TABLE public.ventas_user_user_permissions;

CREATE TABLE public.ventas_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT ventas_user_user_permiss_user_id_permission_id_5128be5d_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT ventas_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT ventas_user_user_per_permission_id_3122134d_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT ventas_user_user_permissions_user_id_38f3971c_fk_ventas_user_id FOREIGN KEY (user_id) REFERENCES public.ventas_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ventas_user_user_permissions_permission_id_3122134d ON public.ventas_user_user_permissions USING btree (permission_id);
CREATE INDEX ventas_user_user_permissions_user_id_38f3971c ON public.ventas_user_user_permissions USING btree (user_id);

-- DROP TYPE public."estado_metodo";

CREATE TYPE public."estado_metodo" AS ENUM (
	'activo',
	'inactivo',
	'vencido');

-- DROP TYPE public."estado_pedido";

CREATE TYPE public."estado_pedido" AS ENUM (
	'Pendiente de pago',
	'Procesando',
	'Despachado',
	'Entregado',
	'Entrega fallida',
	'Cancelado',
	'Reembolsado');

-- DROP TYPE public."estado_producto";

CREATE TYPE public."estado_producto" AS ENUM (
	'activo',
	'inactivo',
	'eliminado');

-- DROP TYPE public."estado_sesion";

CREATE TYPE public."estado_sesion" AS ENUM (
	'activa',
	'convertida',
	'expirada');

-- DROP TYPE public."estado_transaccion";

CREATE TYPE public."estado_transaccion" AS ENUM (
	'pendiente',
	'pagado',
	'error');

-- DROP TYPE public."tipo_documento";

CREATE TYPE public."tipo_documento" AS ENUM (
	'boleta',
	'factura');

-- DROP TYPE public."tipo_metodo_pago";

CREATE TYPE public."tipo_metodo_pago" AS ENUM (
	'tarjeta_credito',
	'tarjeta_debito',
	'cuenta_corriente');

-- DROP TYPE public."tipo_operacion";

CREATE TYPE public."tipo_operacion" AS ENUM (
	'venta',
	'ingreso',
	'ajuste',
	'devolucion',
	'merma');
