# Generated by Django 5.2.7 on 2025-10-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('calle', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('costo_envio', models.IntegerField(default=2990)),
                ('transbank_token', models.CharField(blank=True, max_length=255, null=True)),
                ('transbank_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='pendiente', max_length=50)),
                ('cliente_persona_id', models.IntegerField(blank=True, null=True)),
                ('cliente_empresa_id', models.IntegerField(blank=True, null=True)),
                ('carrito_data', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checkout_session',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
