# Generated by Django 5.2.7 on 2025-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='rut',
            field=models.CharField(default=99999990, max_length=12),
            preserve_default=False,
        ),
    ]
